config/routes.rb
Rails.application.routes.draw do
  resources :actions
  resources :moms
  resources :meets
  resources :agendas
  devise_for :users

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  get 'home/new'
  get 'home/delete'
  get 'home/delete2'
  get 'home/see_your'
  get 'admin/index'
  get 'admin/edit'
  get 'admin/update'
  get 'admin/new'
  get 'admin/sign_out2'
  get 'home/index2'
  post '/admin/new', to: 'admin#create'
  resources :admin, only: [:edit, :update]

end

app/views/admin/edit.html.erb
<%= form_for @user, url: admin_path(@user), method: :put do |f| %>

 <%= hidden_field_tag :authenticity_token, form_authenticity_token %>


<div class="card w-50 justify-content-center" style="color:black">
<div class="card-header">
    <h2 style="text-center"> Edit User </h2>


  <div>
    <%= f.label :email %>
     <p style="text-center"><%= f.email_field :email %></p>
  </div>

  <div>
    <%= f.label :role %>
   <p style="text-center"> <%= f.text_field :role %></p>

  <div>
  <%= f.label :status %>
    <p style="text-center">
    <%=
      f.select(:status,options_for_select([
      ['False',false] , ['True',true] ]  ))  
    %>
    </p>
  </div>



  
  <div>
    <%= f.submit %>
  </div>


</div>
</div>
<% end %>

app/views/admin/index.html.erb
<strong>All Users</strong>
<table class="table">
  <thead class="thead-dark">
    <tr>

      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">status</th>
      <th scope="col">Edit</th>

    </tr>
  </thead>
  <tbody>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.status %></td>
        <td> <%= link_to 'Edit', admin_edit_path(:id => user.id), class:"btn btn-dark" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/new.html.erb
<h2>Sign up</h2>

<%= form_for @user do |f|  %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>
 
  <div class="field">
     <%= f.label :role %><br />
     <%= f.select(:role,options_for_select([ ['Chairperson','chairperson'] , ['HOD','hod'] , ['Director','director'] , ['Help_person' , 'help_person'] , ['admin' , 'admin']   ] )) %>
   </div>

  <div class="field">
     <%= f.label :des %><br />
     <%= f.text_field :des%>
  </div>

  <div class="field">
     <%= f.label :department %><br /> 
     
     <%= f.select(:department,options_for_select([ ['CSE','cse'] , ['EC','ec'] , ['CIVIL','civil'] , ['ELECTRONIC' , 'electronic'] ] )) %>
  </div>
  
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>

<% end %>