config/routes.rb
Rails.application.routes.draw do
  resources :actions
  resources :moms
  resources :meets
  resources :agendas
  devise_for :users

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  get 'home/new'
  get 'home/delete'
  get 'home/delete2'
  get 'home/see_your'
  get 'admin/index'
  get 'admin/edit'
  get 'admin/update'
  get 'admin/new'
  get 'admin/sign_out2'
  get 'home/index2'
  post '/admin/new', to: 'admin#create'
  resources :admin, only: [:edit, :update]

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :set_action, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check


    
  def check
    if current_user.status == true 
        puts("allowed")
    else
      redirect_to root_path
    end
  end
  # GET /actions or /actions.json
  def index
    @actions = Action.all
  end

  # GET /actions/1 or /actions/1.json
  def show
  end

  # GET /actions/new
  def new
    @action = Action.new
  end

  # GET /actions/1/edit
  def edit
  end

  # POST /actions or /actions.json
  def create
    @action = Action.new(action_params)

    respond_to do |format|
      if @action.save
        format.html { redirect_to action_url(@action), notice: "Action was successfully created." }
        format.json { render :show, status: :created, location: @action }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actions/1 or /actions/1.json
  def update
    respond_to do |format|
      if @action.update(action_params)
        format.html { redirect_to action_url(@action), notice: "Action was successfully updated." }
        format.json { render :show, status: :ok, location: @action }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actions/1 or /actions/1.json
  def destroy
    @action.destroy

    respond_to do |format|
      format.html { redirect_to actions_url, notice: "Action was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action
      @action = Action.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def action_params
      params.require(:action).permit(:mom_id, :description, :budget, :deadline, :appointed_person)
    end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/_action.html.erb
<div id="<%= dom_id action %>">
  <p>
    <strong>Mom:</strong>
    <%= action.mom_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= action.description %>
  </p>

  <p>
    <strong>Budget:</strong>
    <%= action.budget %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= action.deadline %>
  </p>

  <p>
    <strong>Appointed person:</strong>
    <%= action.appointed_person %>
  </p>

</div>

app/views/actions/_form.html.erb
<%= form_with(model: action) do |form| %>
  <% if action.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(action.errors.count, "error") %> prohibited this action from being saved:</h2>

      <ul>
        <% action.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :mom_id, style: "display: block" %>
    <%= form.text_field :mom_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :budget, style: "display: block" %>
    <%= form.text_field :budget %>
  </div>

  <div>
    <%= form.label :deadline, style: "display: block" %>
    <%= form.date_field :deadline %>
  </div>

  <div>
    <%= form.label :appointed_person, style: "display: block" %>
    <%= form.text_field :appointed_person %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/actions/edit.html.erb
<h1>Editing action</h1>

<%= render "form", action: @action %>

<br>

<div>
  <%= link_to "Show this action", @action %> |
  <%= link_to "Back to actions", actions_path %>
</div>

app/views/actions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Actions</h1>

<div id="actions">
  <% @actions.each do |action| %>
    <%= render action %>
    <p>
      <%= link_to "Show this action", action %>
    </p>
  <% end %>
</div>

<%= link_to "New action", new_action_path %>

app/views/actions/new.html.erb
<h1>New action</h1>

<%= render "form", action: @action %>

<br>

<div>
  <%= link_to "Back to actions", actions_path %>
</div>

app/views/actions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @action %>

<div>
  <%= link_to "Edit this action", edit_action_path(@action) %> |
  <%= link_to "Back to actions", actions_path %>

  <%= button_to "Destroy this action", @action, method: :delete %>
</div>