config/routes.rb
Rails.application.routes.draw do
  resources :actions
  resources :moms
  resources :meets
  resources :agendas
  devise_for :users

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  get 'home/new'
  get 'home/delete'
  get 'home/delete2'
  get 'home/see_your'
  get 'admin/index'
  get 'admin/edit'
  get 'admin/update'
  get 'admin/new'
  get 'admin/sign_out2'
  get 'home/index2'
  post '/admin/new', to: 'admin#create'
  resources :admin, only: [:edit, :update]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_meet, only: %i[ delete  , delete2 ]
 
  def index
    @meets = Meet.all.order( 'date DESC' )
  end
  
  def index2 
    if current_user.role == "director" || current_user.role == "dean" || current_user.role == "admin"
      @meets = Meet.all.order( 'date DESC' )
    end
    
    if current_user.role == "hod" 
      @meets = Meet.where("(type2 = ? or type2 = ?)", 3, 2)
    end

    if current_user.role == "chairperson" 
      @meets = Meet.where(" type2 = ? " , 3 ).order( 'date DESC' )
    end
    
    
    if current_user.role == "help_person"
       redirect_to root_path , notice =>  "Not Authorized"
    end

  end

  def about
  end

  def see_your
    if current_user.role == "help_person"
        @meet = Meet.all.order( 'date DESC' )
    else
      redirect_to  root_path
    end
  end

  def new
    @agenda = Agenda.new
    @meetid  = params[:id]
    @meet = Meet.find(params[:id])
    @provide_agenda= Agenda.where("user_id = ? and meet_id = ? ", current_user.id , @meetid ) 
  end

  def delete
    @agenda.destroy 
    respond_to do |format|
      format.html { redirect_to home_new_path( :id => @agenda.meet_id ) , notice: "Agenda was successfully destroyed." }
    end
  end


  def delete2
    @agenda.destroy 
    respond_to do |format|
      format.html { redirect_to new_mom_path( :id => @agenda.meet_id ) , notice: "Agenda was successfully destroyed." }
    end
  end




  private 
  def set_meet
    @agenda = Agenda.find(params[:id])
    
  end

  def agenda_params
    params.require(:agenda).permit(:user_id , :content , :meet_id )
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<!DOCTYPE html>  
<html>  
    <head>  
        <title>Meeting Managment System</title> 
        
        <link  rel="stylesheet"  type="text/css" href="style.css" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
       <!-- bootstrap icon css not applied-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/fontawesome.min.css" >
        <!-- bootstrap core css -->
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
        <!-- fonts awesome style -->
        <link href="css/font-awesome.min.css" rel="stylesheet" />
 
    </head>
  
<body>  

<!-- header section and navbar-->    
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3">
<%= link_to 'Meeting Management',root_path, class:"navbar-brand" %>
  <div class="container-fluid">
        
      <% if user_signed_in? %>
          <%= link_to "Sign Out", admin_sign_out2_path,method: :delete,:class => "nav-link active text-primary" %>
          <%= link_to 'Edit Profile',edit_user_registration_path, :class => "nav-link active text-primary"%>
     <% else %>
          <%= link_to 'Sign Up',new_user_registration_path, :class=>"nav-link active text-primary"%>
          <%= link_to 'Sign in', user_session_path, :class=>"nav-link active text-primary" %>
     <% end %>
 
  </div>
</nav>


</header>
<% if user_signed_in? && current_user.status == true %>
<section class="services py-5 bg-light">
<div  class="container ">
  <div>
    <h3 class="text-center">Hello!<span class="text-primary"><%= current_user.role %> ( <%= current_user.department%> )</h1></span></h3>
    <hr / class="w-2 m-auto">
    
  </div>

  <div class="row">

      <%if current_user.role == "dean" || current_user.role == "director"  %>
        <div class="col-sm-12 col-md-4 col-lg-4  col-12">
        <div class="card border-success">
        <div class="card-body">
         <!--<i class="fa fa-user icon"></i> -->
          <h5 class="card-title">Create Meetings</h5>
          <p class="card-text">Dashboard to create meeting.</p>
          <%= link_to " Create Meeting", new_meet_path , :class => "btn btn-primary"%>
        </div>
        </div>
        </div>
        
        <div class="col-sm-12 col-md-4 col-lg-4  col-12">
        <div class="card border-success">
        <div class="card-body">
         <!--<i class="fa fa-user icon"></i> -->
          <h5 class="card-title">Previous Meetings</h5>
          <p class="card-text">See or edit your previous meetings.</p>
        <%= link_to " Details Meeting", meets_path ,:class => "btn btn-primary"%>
        </div>
        </div>
        </div>

        <% end %>

        <%if current_user.role  == "help_person"%>
          <div class="col-sm-12 col-md-4 col-lg-4  col-12">
          <div class="card border-success">
          <div class="card-body">
          <!--<i class="fa fa-user icon"></i> -->
            <h5 class="card-title">Create Minutes of Meeting</h5>
            <p class="card-text">Dashboard to create Minutes of meeting.</p>
            <%= link_to "Miniute of Meeting", home_see_your_path ,:class => "btn btn-primary"%> 
          </div>
          </div>
          </div>

          <div class="col-sm-12 col-md-4 col-lg-4  col-12">
          <div class="card border-success">
          <div class="card-body">
          <!--<i class="fa fa-user icon"></i> -->
            <h5 class="card-title">Edit Minutes</h5>
            <p class="card-text">Edit Minutes of meeting created before.</p>
            <%= link_to "Edit", moms_path ,:class => "btn btn-primary"%> 
          </div>
          </div>
          </div>


          <%end%>       
           <div class="col-sm-12 col-md-4 col-lg-4  col-12">
          <div class="card border-success">
          <div class="card-body">
          <!--<i class="fa fa-user icon"></i> -->
            <h5 class="card-title">Database</h5>
            <p class="card-text">See all meetings.</p>
            <%= link_to "open", home_index2_path ,:class => "btn btn-primary"%> 
          </div>
          </div>
          </div>

          <% if current_user.role=="admin" %>
 
        <div class="col-sm-12 col-md-4 col-lg-4  col-12">
        <div class="card border-success">
        <div class="card-body">
         <!--<i class="fa fa-user icon"></i> -->
          <h5 class="card-title">Admin Dashboard</h5>
          <p class="card-text">Create User / Edit </p> 
          
            <%= link_to "Approve Users", admin_index_path ,:class => "btn btn-primary"%> 

          
        </div>
        </div>
        </div>

        <%end%>
 <%end%>
     </div>

    </div>

</section>



  
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
     
</body> 


</html>

app/views/home/about.html.erb
##about##

app/views/home/index.html.erb
<p style="color: green"><%= notice %></p>
<%if user_signed_in? && current_user.status == true  %>
<h1>INVITATION</h1>
<div>
<table id="example" class="table table-striped table-bordered" style="width:100%">
<input class="form-control" id="myInput" type="text" placeholder="Search..">
         <thead>
            <tr>
                <th>Type</th>
                <th>Date</th>
                <th>Title</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="tableData">
            <div id="addvs">
  <% @meets.each do |meet| %>
<tr>
    <% if meet.type2 == 2 && current_user.role == "hod" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                </td>
    <% end %>





    <% if meet.type2 == 2 && current_user.role == "dean" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                </td>
    <% end %>




    <% if meet.type2 == 3 && current_user.role == "hod" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                </td>
    <% end %>




    <% if meet.type2 == 3 && current_user.role == "chairperson" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                </td>
    <% end %>




    <% if meet.type2 == 3 && current_user.role == "dean" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                </td>
    <% end %>



  
    <% if meet.type2 == 1 && current_user.role == "dean" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                </td>
    <% end %>


  <% if meet.type2 == 1 && current_user.role == "director" %>
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     <%= link_to "Give agenda", home_new_path(:id => meet.id) %> 
                     <%= link_to "Details", meet_path(id:meet.id,format:"pdf") %>
                </td>
    <% end %>




               <% end %>
            </tr>
        </tfoot>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" ></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#tableData tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
</div>

<%else%>


<%if user_signed_in? && current_user.status == false  %>

      your request has been send to admin please wait 

<%end%>


<%if user_signed_in? && current_user.status == nil  %>

      your request has been send to admin please wait 

<%end%>

<h1><strong>HOME</strong> _ PLEASE LOGIN FIRST </h1>

 <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "img1.jpg",width: 1250,height: 400 %>
      <div class="carousel-caption d-none d-md-block">
        <h3></h3>
        <p> Page-1</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "img3.jpg",width: 1250,height: 400 %>
      <div class="carousel-caption d-none d-md-block">
         <h3> </h3>
        <p>Page-2</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "img2.jpg",width: 1250,height: 400 %>
      <div class="carousel-caption d-none d-md-block">
         <h3> </h3>
        <p>Page-3</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


     <!-- contact us-->
<section class="team my-5 text-center " data-aos="fade-up" data-aos-offset="200">
    <div class="container">
    <div data-aos="fade-up">
        <h3>Our<span class="text-primary"> Teams</span></h3>
        <hr / class="w-2 m-auto">
    </div> 

    <div class="row"> 
    <div class="col-sm-12 col-md-3 col-lg-3  col-12"> 
            <div class="card">
            <div class="card-body">
            <%= image_tag "hk1.jpg",class:"img-fluid rounded-circle border border-primary" %>
            <!--<i class="fa fa-user icon"></i> -->
                <h5 class="card-title mt-4">SYAM KUMAR KS </h5>
                <p class="card-text">Frontend/Backend Devloper</p>
               <h6>Example1@gmail.com</h6>
            </div>
            </div>  
    
    </div>
    <div class="col-sm-12 col-md-3 col-lg-3  col-12">
            <div class="card">
            <div class="card-body">
            <%= image_tag "hk1.jpg",class:"img-fluid rounded-circle border border-primary" %>
            <!--<i class="fa fa-user icon"></i> -->
                <h5 class="card-title mt-4">AASHISH CHAUHAN</h5>
                <p class="card-text"> Frontend/Backend Devloper</p>
               <h6>Example1@gmail.com</h6>
            </div>
            </div>
    
        </div>
    <div class="col-sm-12 col-md-3 col-lg-3  col-12"> 
        <div class="card">
            <div class="card-body">
            <%= image_tag "hk1.jpg",class:"img-fluid rounded-circle border border-primary" %>
        
            <!--<i class="fa fa-user icon"></i> -->
                <h5 class="card-title mt-4">SULALA SALEEM P</h5>
                <p class="card-text">Frontend/Backend Devloper</p>
                <h6>Example1@gmail.com</h6>
            </div>
            </div>   
            
    
    </div>
    <div class="col-sm-12 col-md-3 col-lg-3  col-12"> 
        <div class="card">
            <div class="card-body">
            <%= image_tag "hk1.jpg",class:"img-fluid rounded-circle border border-primary" %>
            <!--<i class="fa fa-user icon"></i> -->
                <h5 class="card-title mt-4">YATTANDEEP SINGH</h5>
                <p class="card-text">Frontend/Backend Devloper</p>
                <h6>Example1@gmail.com</h6>
            </div>
            </div>
    
    </div>
    </div>
    </div>


    <div class="col-sm-12 col-md-3 col-lg-3  col-12"> 
        <div class="card">
            <div class="card-body">
            <%= image_tag "hk1.jpg",class:"img-fluid rounded-circle border border-primary" %>
            <!--<i class="fa fa-user icon"></i> -->
                <h5 class="card-title mt-4">ABHIMANYU SINGH</h5>
                <p class="card-text">Frontend/Backend Devloper</p>
                <h6>Example1@gmail.com</h6>
            </div>
            </div>
 </section>
<%end%>
    <section>
    <div class="container text-center" data-aos="fade-up" data-aos-offset="100">
    <h1>About <span class="text-primary">us</span>....</h1>
    <!-- <p>Team Members:</p> -->
    <h6>Prepared by:</h6>
    <h3>1. SYAM KUMAR KS ( M220118CS)</h3>
    <h3>2. AASHISH CHAUHAN ( M220452CS )</h3>
    <h3>3. SULALA SALEEM P ( M220118CS )</h3>
    <h3>4. YATTANDEEP SINGH (M220287CS)</h3>
    <h3>5. ABHIMANYU SINGH (M220278CS)</h3>

    <h4>Course : CS6154D Topics in Database


    </div>
    </section>

app/views/home/index2.html.erb
<p style="color: green"><%= notice %></p>
<h1>Database</h1>
<div>
<table id="example" class="table table-striped table-bordered" style="width:100%">
<input class="form-control" id="myInput" type="text" placeholder="Search..">
      
        <thead>
            <tr>
                <th>Type</th>
                <th>Date</th>
                <th>Title</th>
                <th>Description</th>
                <th>Details</th>              
            </tr>
        </thead>
        <tbody id="tableData">            
            <div id="addvs">
 
  <% @meets.each do |meet| %>
<tr>  
 
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     
      <%= link_to "Details", meet %> 
      <%= link_to "Print", meet_path(id:meet.id,format:"pdf") %> 
                </td>

               <% end %>
            </tr>
        </tfoot>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" ></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#tableData tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
</div>

app/views/home/new.html.erb
<%= form_for @agenda do |form| %>
  <div>
    <%= form.number_field :user_id , value: current_user.id  , type: :hidden %>
    <%= form.number_field :meet_id , value: @meetid , type: :hidden %>
  </div>
</br>

  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-7">

        <h1 class="text-white mb-4">Create Agendas</h1>

        <div class="card" style="border-radius: 15px;">
          <div class="card-body">


         
              <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">
              <h6 class="mb-0">Meeting Description</h6>
              </div>
              <div class="col-md-9 pe-5">
              <input class="form-control" type="text" placeholder = "<%= (@meet.description) %>"  readonly >
              </div>
              </div>


              <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">
              <h6 class="mb-0">Meeting Type</h6>
              </div>
              <div class="col-md-9 pe-5">
              <input class="form-control" type="text" placeholder = "<% if @meet.type2 == 1 %> For All Dean <%end%>
              <% if @meet.type2 == 2 %> For all HODs <%end%>
              <% if @meet.type2 == 3 %> For All Chairperson + HOD <%end%> "  readonly >
              </div>
              </div>

               
              <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">
              <h6 class="mb-0">Add Agenda here</h6>
              </div>
              <div class="col-md-9 pe-5">

              <%= form.text_area :content, class: "form-control", type: "text" %>

              </div>
              </div>
              
              <%= form.submit "Create" ,  class: "btn btn-primary" %>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>







<table id="example" class="table table-striped table-bordered" style="width:100%">
<thead class="thead-dark">

    <tr>
      <th scope="col">Previous Agenda</th>
      
      <th scope="col">Action</th>
    </tr>

  </thead>

        <tbody>
            <div>


   <% @provide_agenda.each do |x|%>
      <tr>
      <td>  <%= x.content %> </td>
      <td><%= link_to 'delete', home_delete_path(:id => x.id), class:"btn btn-dark" %></td>
      </tr>
    <%end%>
    
    </tfoot>
    </table>
  </div>

<% end %>

app/views/home/see_your.html.erb
<p style="color: green"><%= notice %></p>
<table id="example" class="table table-striped table-bordered" style="width:100%">
<input class="form-control" id="myInput" type="text" placeholder="Search..">
<thead class="thead-dark">

    <tr>
    
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">For</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

        <tbody id="tableData">
            <div id="addvs">
 <% @meet.each do |meet| %>
    <tr>
      <td> <%= meet.title %> </td>
      <td> <%= meet.description %> </td>
      <td> <%= meet.date %> </td>
      <td> 
                      
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

      </td>
      <td>
    <%= link_to 'create minute', new_mom_path(:id => meet.id), class:"btn btn-dark" %> </td>
    </tr>
<%end%>

        </tfoot>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" ></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#tableData tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
</div>