config/routes.rb
Rails.application.routes.draw do
  resources :actions
  resources :moms
  resources :meets
  resources :agendas
  devise_for :users

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  get 'home/new'
  get 'home/delete'
  get 'home/delete2'
  get 'home/see_your'
  get 'admin/index'
  get 'admin/edit'
  get 'admin/update'
  get 'admin/new'
  get 'admin/sign_out2'
  get 'home/index2'
  post '/admin/new', to: 'admin#create'
  resources :admin, only: [:edit, :update]

end

app/models/meet.rb
class Meet < ApplicationRecord
    has_many :agendas , :dependent => :destroy 
    accepts_nested_attributes_for :agendas
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check
  before_action :check2 , only: %i[ new create  ]   
 
  def check2
    if current_user.role == "dean" || current_user.role == "director" 
        puts("allowed")
    else
      redirect_to root_path , notice => "Not allowed to create meetings"
    end

  end
    
  def check
    if current_user.status == true 
        puts("allowed")
    else
      redirect_to root_path
    end
  end



  def index
    @meets = Meet.where(  "user_id = ?" , current_user.id  )
  end

  def show
    @all_agenda = Agenda.where( "meet_id = ?" , @meet.id )
    @mom = Mom.where( " meet_id = ? " ,@meet.id )
    @action = Action.where( " mom_id = ? " ,@mom.ids )

    if @meet.type2 ==1 # Dean Meeting
      @Participents=User.where(role:["Director","Dean"])
    elsif @meet.type2 ==2 # Hod 
      @Participents=User.where(role:["Director","Hod"])
    elsif @meet.type2 ==3 # Hod & Chairpersons 
      @Participents=User.where(role:["Director","Hod","Chairperson"])
    end
#pdf 
    respond_to do |format|
      format.html
      format.pdf do
        pdf=Prawn::Document.new(:page_size => "A4", :page_layout => :portrait)     
        #pdf.stroke_axis
        pdf.image("./app/assets/images/logo-white.jpg",width:400,height:50,position: :center)
        pdf.move_down(10)
        pdf.stroke_horizontal_rule()
        pdf.move_down(10)
        pdf.font('Helvetica', size: 18)
        pdf.text( "<u>Minutes of Meeting</u>",align: :center,inline_format: true)
        pdf.font('Times-Roman', size: 12)
        pdf.move_down(10)
        pdf.text "Meeting Title   :#{@meet.title}"
        pdf.move_down(5)
        pdf.text "Meeting Date    :#{@meet.date.strftime("%d-%m-%Y")}"
        pdf.move_down(5)
        pdf.text "Meeting Description    :#{@meet.description}"
        pdf.move_down(5)
        pdf.text "For    :#{
          

        if @meet.type2 ==1 # Dean Meeting
            "Dean Meeting"
        elsif @meet.type2 ==2 # Hod 
            "Hod Meeting"
        elsif @meet.type2 ==3 # Hod & Chairpersons 
            "Hod Chairperson Meeting"
        end        
        
        }"
        pdf.move_down(5)
        #pdf.text "Meeting Venue    :#{@mom.venue}"      
        venue="";
        report="";
        @mom.each do |item|
          venue=item.venue
          report=item.report
        end
        pdf.text("Meeting Venue    :#{venue}")
        pdf.font('Helvetica', size: 14)
        pdf.text("<u>Agenda</u>",align: :left,inline_format: true,indent_paragraphs: 60) 
        pdf.font('Times-Roman', size: 12)
        slno=1
        pdf.move_down(10)
        @all_agenda.each do |item|
          pdf.text("#{slno} : #{item.content}")
          pdf.move_down(5)
          slno+=1
        end
        pdf.move_down(10)
        pdf.font('Helvetica', size: 14)
        pdf.text("<u>Decisions Taken</u>",align: :left,inline_format: true,indent_paragraphs: 60) 
        pdf.font('Times-Roman', size: 12)
        slno=1
        head_row=["Sl NO", "Description", "Budget", "Charge Assigned","Dead Line"]
        line_item_rows=[head_row]
        @action.each do |item|
          line_item_rows.push([slno,item.description, item.budget, item.appointed_person, item.deadline])
            slno+=1
        end
        pdf.move_down(20)
        pdf.table(line_item_rows,:header => true,:column_widths => [30,150, 100, 100,100])
        pdf.move_down(10)
        pdf.font('Helvetica', size: 16)
        pdf.text("<u>Report</u>",align: :left,inline_format: true,indent_paragraphs: 60) 
        pdf.font('Times-Roman', size: 12)
        pdf.text("#{report}",indent_paragraphs: 60)

        send_data pdf.render ,filename:"Meeting_Minutes#{@meet.title}_#{@meet.date.strftime("%d-%m-%Y")}.pdf",
        type:"application/pdf",disposition:"inline"
       
      end
      end




  end

  def new
    @meet = Meet.new
  end

  def edit
      @all_agenda = Agenda.where("meet_id = ?" , @meet.id)
  end

  def create
    @meet = Meet.new(meet_params)
    respond_to do |format|
      if @meet.save
        format.html { redirect_to meet_url(@meet), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to meet_url(@meet), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Mom.where(:meet_id => @meet.id).destroy_all
    @meet.destroy
    respond_to do |format|
      format.html { redirect_to meets_url, notice: "Meeting + Agendas was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_meet
      @meet = Meet.find(params[:id])
    end

    def meet_params
      params.require(:meet).permit(:user_id, :date, :title, :description ,:type2)
    end
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/meets/_form.html.erb
<%= form_with(model: meet) do |form| %>
  <% if meet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

    </div>
  <% end %>

<section class="vh-100" style="background-color: #2779e2;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-5">

        <h1 class="text-white mb-4">Create/Edit New Meeting</h1>

        <div class="card" style="border-radius: 15px;">
          <div class="card-body">

            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0"> Set Date and Time </h6>
              <%= form.number_field :user_id ,value:current_user.id , type: :hidden %>
                 <%= form.number_field :user_id , value: current_user.id ,type: :hidden %>
              </div>
              <div class="col-md-9 pe-5">
              
    <%= form.datetime_field :date %>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Title</h6>

              </div>
              <div class="col-md-9 pe-5">
                 <p> <%= form.text_field :title %></p>
              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Description</h6>

              </div>
              <div class="col-md-9 pe-5">

                    <%= form.text_area :description %>
              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">For</h6>

              </div>
              <div class="col-md-9 pe-5">

    <%=
      form.select(:type2,options_for_select([
      ['For Deans',1] , ['For HODs',2] ,['For Chairpersons + All HOds',3] ]  ))  
    %>


              </div>
            </div>

            <hr class="mx-n3">

            <div class="px-5 py-4">

             <%= form.submit "Create" , class: "btn btn-secondary"  %>
              
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>


<%end%>

app/views/meets/_meet.html.erb
<div id="<%= dom_id meet %>">
    <p>
  <strong>ID:</strong>
    <%= meet.id %>

    <strong>User:</strong>
    <%= meet.user_id %>
 
    <strong>Date:</strong>
    <%= meet.date %>
 
    <strong>Title:</strong>
    <%= meet.title %>

    <strong>Description:</strong>
    <%= meet.description %>
  
    <strong>Type:</strong>
    <% if meet.type2 == 1 %>
        For All Deans
    <%end%>

    <% if meet.type2 == 2 %>
  
  For all HODs
    <%end%>


    <% if meet.type2 == 3 %>

For All Chairperson + HOD
    <%end%>
  </p>
</div>

app/views/meets/edit.html.erb
<h1>Editing meet</h1>

<%= render "form", meet: @meet %>

<br>

<div>
  <%= link_to "Show this meet", @meet %> |
  <%= link_to "Back to meets", meets_path %>
</div>

app/views/meets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Previous Meeting</h1>
<div>
<table id="example" class="table table-striped table-bordered" style="width:100%">
<input class="form-control" id="myInput" type="text" placeholder="Search..">
      
        <thead>
            <tr>
                <th>Type</th>
                <th>Date</th>
                <th>Title</th>
                <th>Description</th>
                <th>Details</th>
              
            </tr>
        </thead>
        <tbody id="tableData">
            
            <div id="addvs">
 
  <% @meets.each do |meet| %>
<tr>  
 
                <td>
                <%if meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>

                </td>
                <td><%= meet.date%></td>
                 <td><%= meet.title%></td>
                <td><%= meet.description%></td>
                <td>
                     
      <%= link_to "Details", meet %> 
      <%= link_to "Print", meet_path(id:meet.id,format:"pdf") %> 
                </td>

               <% end %>
            </tr>
        </tfoot>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" ></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#tableData tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
</div>

app/views/meets/new.html.erb
<%= render "form", meet: @meet %>

<br>
<div>
  <%= link_to "Back to meets", meets_path %>
</div>

app/views/meets/show.html.erb
<p style="color: green"><%= notice %></p>
<strong>MEETING </strong>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">For</th>
     <% if current_user.id == @meet.user_id%> <th scope="col">Delete</th> <%end%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @meet.title %> </td>
      <td> <%= @meet.description %> </td>
      <td> <%= @meet.date %> </td>
      <td>              
                <%if @meet.type2 == 1%>
                For Deans
                <% end %>
                
                <%if @meet.type2 == 2%>
                For All HODs 
                <% end %>
                
                <%if @meet.type2 == 3%>
                For all HODs and Chairperson
                <% end %>
      </td>
      <% if current_user.id == @meet.user_id%>
      <td> <%= button_to "Destroy this meeting", @meet, method: :delete , :class => "btn btn-danger"%> </td>
      <%end%>
    </tr>
    
  </tbody>
</table>











<% @mom.each do |x| %>   
<dl class="row">
  <dt class="col-sm-3">Venue</dt>
  <dd class="col-sm-9">
 <%= x.venue%>
</dd>
  <dt class="col-sm-3">Report</dt>
  <dd class="col-sm-9">
   <p> <%= x.report %></p>
  </dd>
  </dl>
  </dd>
<% end %> 



</br>
<strong>SUGGESTED AGENDAS</strong>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Agenda</th>
      <th scope="col">Created At</th>
      <th scope="col">Updated At</th>
    </tr>
  </thead>
  <tbody>

   <% @all_agenda.each do |x| %>
    <tr>
      <td> <%= x.content %> </td>
      <td> <%= x.created_at %> </td>
      <td> <%= x.updated_at %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

</br>
<strong>Decisions Taken</strong>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Appointed</th>
      <th scope="col">Budget</th>
    </tr>
  </thead>
  <tbody>

<% @action.each do |action| %> 
    <tr>
      <td> <%= action.description %> </td>
      <td> <%= action.appointed_person %> </td>
      <td> <%= action.budget %> </td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= link_to "Back", meets_path , :class => "btn btn-secondary" %>

<%= link_to "Edit/Reshedule this meeting", edit_meet_path(@meet) ,:class => "btn btn-primary"%> 